### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by megapro17** [Magisk-Modules-Repo/APFE#3]
After installing module from magisk nothing changed. Fonts stayed like it was before.
Tested on kenzo and tissot running LineageOS 16

**Comment by petsboem** [comment]
Same on Samsung A6, no change in fonts or emoij.

**Comment by joeyhuab** [comment]
Are you guys both on Pie?

> After installing module from magisk nothing changed. Fonts stayed like it was before.
> Tested on kenzo and tissot running LineageOS 16

You're on Pie. LOS 16 is Pie. You don't need this module.

**Comment by joeyhuab** [comment]
> Same on Samsung A6, no change in fonts or emoij.

I'm guessing you're on Pie as well? If so, your fonts are already updated.

**Comment by megapro17** [comment]
I'm on pie, but my fonts are old

**Comment by joeyhuab** [comment]
> I'm on pie, but my fonts are old

It means they're not outdated since the fonts didn't change at all. :)
